south = {
    1: "Houston",
    2: "Marquette",
    3: "Kentucky",
    4: "Duke",
    5: "Wisconsin",
    6: "Texas Tech",
    7: "Florida",
    8: "Nebraska",
    9: "Texas A&M",
    10: "Colorado Boulder",
    11: "NC State",
    12: "James Madison",
    13: "Vermont",
    14: "Oakland",
    15: "Western KY",
    16: "Longwood",
    "play_in": "Boise State",
    "play_in_rank": 10,
}

east = {
    1: "UConn",
    2: "Iowa State",
    3: "Illinois",
    4: "Auburn",
    5: "SDSU",
    6: "BYU",
    7: "Washington State",
    8: "Memphis",
    9: "FAU",
    10: "Drake",
    11: "Duquesne",
    12: "UAB",
    13: "Yale",
    14: "Morehead State",
    15: "South Dakota State",
    16: "Stetson",
    "play_in": "Virginia",
    "play_in_rank": 16,
}

midwest = {
    1: "Purdue",
    2: "Tennessee",
    3: "Creighton",
    4: "Kansas",
    5: "Gonzaga",
    6: "South Carolina",
    7: "Texas",
    8: "Utah State",
    9: "TCU",
    10: "CSU",
    11: "Oregon",
    12: "McNeese",
    13: "Samford",
    14: "Akron",
    15: "Saint Peter's",
    16: "Grambling State",
    "play_in": "Montana State",
    "play_in_rank": 16,
}

west = {
    1: "UNC",
    2: "Arizona",
    3: "Baylor",
    4: "Alabama",
    5: "St. Mary's",
    6: "Clemson",
    7: "Dayton",
    8: "Mississippi State",
    9: "Michigan State",
    10: "Nevada",
    11: "New Mexico",
    12: "Grand Canyon",
    13: "Charleston",
    14: "Colgate",
    15: "Long Beach State",
    16: "Wagner",
    "play_in": "Howard",
    "play_in_rank": 16,
}
