west = {
    1: "Gonzaga",
    2: "Duke",
    3: "Texas Tech",
    4: "Arkansas",
    5: "UConn",
    6: "Alabama",
    7: "Michigan State",
    8: "Boise State",
    9: "Memphis",
    10: "Davidson",
    11: "Notre Dame",
    12: "NM State",
    13: "Vermont",
    14: "Montana State",
    15: "CSUF",
    16: "Georgia State",
    "play_in": "Rutgers",
    "play_in_rank": 11,
}

east = {
    1: "Baylor",
    2: "Kentucky",
    3: "Purdue",
    4: "UCLA",
    5: "St. Mary's",
    6: "Texas",
    7: "Murray State",
    8: "UNC",
    9: "Marquette",
    10: "San Francisco",
    11: "Virginia Tech",
    12: "Indiana",
    13: "Akron",
    14: "Yale",
    15: "Saint Peter's",
    16: "Norfolk State",
    "play_in": "Wyoming",
    "play_in_rank": 12,
}

south = {
    1: "Arizona",
    2: "Villanova",
    3: "Tennessee",
    4: "Illinois",
    5: "Houston",
    6: "CSU",
    7: "Ohio State",
    8: "Seton Hall",
    9: "TCU",
    10: "Loyola Chicago",
    11: "Michigan",
    12: "UAB",
    13: "Chattanooga",
    14: "Longwood",
    15: "Delaware",
    16: "Wright State",
    "play_in": "Bryant",
    "play_in_rank": 16,
}

midwest = {
    1: "Kansas",
    2: "Auburn",
    3: "Wisconsin",
    4: "Providence",
    5: "Iowa",
    6: "LSU",
    7: "USC",
    8: "SDSU",
    9: "Creighton",
    10: "Miami",
    11: "Iowa State",
    12: "Richmond",
    13: "South Dakota State",
    14: "Colgate",
    15: "Jacksonville State",
    16: "Texas Southern",
    "play_in": "AMCC",
    "play_in_rank": 16,
}
