south = {
    1: "Alabama",
    2: "Arizona",
    3: "Baylor",
    4: "Virginia",
    5: "SDSU",
    6: "Creighton",
    7: "Missouri",
    8: "Maryland",
    9: "West Virginia",
    10: "Utah State",
    11: "NC State",
    12: "Charleston",
    13: "Furman",
    14: "UCSB",
    15: "Princeton",
    16: "AMCC",
    "play_in": "Southeast Missouri State",
    "play_in_rank": 16,
}

east = {
    1: "Purdue",
    2: "Marquette",
    3: "Kansas State",
    4: "Tennessee",
    5: "Duke",
    6: "Kentucky",
    7: "Michigan State",
    8: "Memphis",
    9: "FAU",
    10: "USC",
    11: "Providence",
    12: "Oral Roberts",
    13: "Louisiana-Lafayette",
    14: "Montana State",
    15: "Vermont",
    16: "Texas Southern",
    "play_in": "Fairleigh Dickinson",
    "play_in_rank": 16
}

midwest = {
    1: "Houston",
    2: "Texas",
    3: "Xavier",
    4: "Indiana",
    5: "Miami",
    6: "Iowa State",
    7: "Texas A&M",
    8: "Iowa",
    9: "Auburn",
    10: "Penn State",
    11: "Mississippi State",
    12: "Drake",
    13: "Kent State",
    14: "Kennesaw State",
    15: "Colgate",
    16: "Northern Kentucky",
    "play_in": "Pitt",
    "play_in_rank": 11,
}

west = {
    1: "Kansas",
    2: "UCLA",
    3: "Gonzaga",
    4: "UConn",
    5: "St. Mary's",
    6: "TCU",
    7: "Northwestern",
    8: "Arkansas",
    9: "Illinois",
    10: "Boise State",
    11: "Arizona State",
    12: "VCU",
    13: "Iona",
    14: "Grand Canyon",
    15: "UNC Asheville",
    16: "Howard",
    "play_in": "Nevada",
    "play_in_rank": 11,
}