south = {
    1: "University of Alabama",
    2: "University of Arizona",
    3: "Baylor University",
    4: "University of Virginia",
    5: "San Diego State University",
    6: "Creighton University",
    7: "University of Missouri",
    8: "University of Maryland",
    9: "West Virginia University",
    10: "Utah State University",
    11: "North Carolina State University",
    12: "Charleston University",
    13: "Furman University",
    14: "University of California, Santa Barbara",
    15: "Princeton University",
    16: "Texan A&M-Corpus Christi",
    "play_in": "Southeast Missouri State University",
    "play_in_rank": 16,
}

east = {
    1: "Purdue University",
    2: "Marquette University",
    3: "Kansas State University",
    4: "University of Tennessee",
    5: "Duke University",
    6: "University of Kentucky",
    7: "Michigan State University",
    8: "Memphis University",
    9: "Florida Atlantic University",
    10: "University of Southern California",
    11: "Providence University",
    12: "Oral Roberts University",
    13: "Louisiana-Lafayette University",
    14: "Montana State University",
    15: "University of Vermont",
    16: "Texas Southern University",
    "play_in": "Fairleigh Dickinson",
    "play_in_rank": 16
}

midwest = {
    1: "University of Houston",
    2: "University of Texas",
    3: "Xavier University",
    4: "University of Indiana",
    5: "University of Miami",
    6: "Iowa State University",
    7: "Texas A&M University",
    8: "University of Iowa",
    9: "Auburn University",
    10: "Pennsylvania State University",
    11: "Mississippi State University",
    12: "Drake University",
    13: "Kent State University",
    14: "Kennesaw St University",
    15: "Colgate University",
    16: "University of Northern Kentucky",
    "play_in": "University of Pittsburgh",
    "play_in_rank": 11,
}

west = {
    1: "University of Kansas",
    2: "University of California, Los Angeles",
    3: "Gonzaga University",
    4: "University of Connecticut",
    5: "Saint Mary's University",
    6: "Texas Christian University",
    7: "Northwestern University",
    8: "University of Arkansas",
    9: "University of Illinois Urbana–Champaign",
    10: "Boise State University",
    11: "Arizona State University",
    12: "Virginia Commonwealth University",
    13: "Iona University",
    14: "Grand Canyon University",
    15: "University of North Carolina at Asheville",
    16: "Howard University",
    "play_in": "University of Nevada",
    "play_in_rank": 11,
}