# Generated by Django 4.2.5 on 2023-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marchmadness",
            "0002_apranking_tournamentranking_school_championship_wins_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
