# Generated by Django 4.2.5 on 2023-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0003_alter_school_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="home_arena",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="location",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="primary_color",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="secondary_color",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
