# Generated by Django 4.2.5 on 2023-09-24 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0007_game_distinct_home_away"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="away_team",
            new_name="opponent",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="away_score",
            new_name="opponent_score",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="home_team",
            new_name="school_name",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="home_score",
            new_name="school_score",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="distinct_home_away",
            new_name="win",
        ),
    ]
