# Generated by Django 4.2.5 on 2023-09-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0008_rename_away_team_game_opponent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apranking",
            name="ranking_id",
        ),
        migrations.RemoveField(
            model_name="tournamentranking",
            name="ranking_id",
        ),
        migrations.AddField(
            model_name="apranking",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournamentranking",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
