# Generated by Django 4.2.5 on 2023-09-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0011_tournamentranking_play_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="home_game",
            field=models.BooleanField(default=True),
        ),
    ]
