# Generated by Django 4.2.5 on 2023-09-30 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marchmadness", "0012_game_home_game"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentranking",
            old_name="conference",
            new_name="region",
        ),
    ]
